services:
  - type: web
    name: medidocs
    runtime: node
    buildCommand: npm ci && npm run build && npm install -g serve
    startCommand: serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
