// Custom icons export - from @heroicons/react v2
// Using ONLY verified icon names from the library
import { 
  HomeIcon,
  ClockIcon,
  PlayIcon,
  PlayCircleIcon,
  UsersIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  CurrencyDollarIcon,
  CheckIcon,
  XMarkIcon,
  UserIcon,
  CogIcon,
  Bars3Icon,
  ChevronRightIcon,
  ChevronDownIcon,
  StarIcon,
  HeartIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  RefreshIcon,
  SearchIcon,
  FilterIcon,
  BellIcon,
  CalendarIcon,
  ClipboardListIcon,
  CreditCardIcon,
  WalletIcon,
  BanknotesIcon,
  GlobeAltIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  ChartBarIcon,
  ClipboardCheckIcon,
  BanIcon,
  ThumbUpIcon,
  ThumbDownIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  IdentificationIcon,
  DocumentTextIcon,
  FolderIcon,
  ArchiveIcon,
  TrashIcon,
  PencilIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  CursorClickIcon,
  ExclamationTriangleIcon,
  ServerIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  CodeIcon,
  TerminalIcon,
  DatabaseIcon,
  QuestionMarkCircleIcon,
  DocumentIcon,
} from '@heroicons/react/24/outline';

// Create aliases for backward compatibility
const TrendingUpIcon = ArrowTrendingUpIcon;
const TrendingDownIcon = ArrowTrendingDownIcon;
const DollarSignIcon = CurrencyDollarIcon;
const XIcon = XMarkIcon;
const MenuIcon = Bars3Icon;
const MailIcon = EnvelopeIcon;
const HelpCircle = QuestionMarkCircleIcon;
const FileText = DocumentTextIcon;
const LocationMarkerIcon = MapIcon;

export {
  HomeIcon,
  ClockIcon,
  PlayIcon,
  PlayCircleIcon,
  UsersIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  CurrencyDollarIcon,
  DollarSignIcon,
  CheckIcon,
  XIcon,
  XMarkIcon,
  UserIcon,
  CogIcon,
  MenuIcon,
  Bars3Icon,
  ChevronRightIcon,
  ChevronDownIcon,
  StarIcon,
  HeartIcon,
  MailIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapIcon,
  LocationMarkerIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  RefreshIcon,
  SearchIcon,
  FilterIcon,
  BellIcon,
  CalendarIcon,
  ClipboardListIcon,
  CreditCardIcon,
  WalletIcon,
  BanknotesIcon,
  GlobeAltIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  ChartBarIcon,
  ClipboardCheckIcon,
  BanIcon,
  ThumbUpIcon,
  ThumbDownIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  IdentificationIcon,
  DocumentTextIcon,
  FileText,
  FolderIcon,
  ArchiveIcon,
  TrashIcon,
  PencilIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  CursorClickIcon,
  ExclamationTriangleIcon,
  ServerIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  CodeIcon,
  TerminalIcon,
  DatabaseIcon,
  HelpCircle,
  DocumentIcon,
};

// Also export some solid icons
export {
  StarIcon as StarIconSolid,
  HeartIcon as HeartIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
} from '@heroicons/react/24/solid';
